### ISSUE TITLE
how to export?

### ISSUE THREAD

**Issue by Sapu98** [Minecraftfunize/Youtube-Hacked-Client-1.8#17]
i need help pls, i want to export my client  but how?
i tryed to export it but when i try to play the game crash and it say:
Exception in thread "Client thread" java.lang.ExceptionInInitializerError
	at net.minecraft.util.StatCollector.<clinit>(StatCollector.java:5)
	at net.minecraft.item.Item.getUnlocalizedNameInefficiently(Item.java:293)
	at net.minecraft.item.Item.getItemStackDisplayName(Item.java:416)
	at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:590)
	at net.minecraft.item.ItemStack.getChatComponent(ItemStack.java:1031)
	at net.minecraft.stats.StatList.func_151181_c(StatList.java:184)
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:112)
	at net.minecraft.init.Bootstrap.register(Bootstrap.java:560)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(Main.java:114)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at org.apache.commons.io.IOUtils.readLines(IOUtils.java:986)
	at net.minecraft.util.StringTranslate.<init>(StringTranslate.java:42)
	at net.minecraft.util.StringTranslate.<clinit>(StringTranslate.java:28)
	... 10 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by valli308** [comment]
I got the Error, when I didn't have the pack.png & assets folder from the normal minecraft jar in the jar of my client.

**Comment by ukwilliam** [comment]
valli308 is correct, drag the assets folder in.

**Comment by Ludde856x** [comment]
Hey i get this error Exception in thread "main" java.lang.NoClassDefFoundError: cbl
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
	at java.lang.Class.getMethod0(Class.java:3010)
	at java.lang.Class.getMethod(Class.java:1776)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: cbl
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
pls help

**Comment by Minecraftfunize** [comment]
Watch the exporting video

**Comment by TheShadowGamer06** [comment]
i dont have a assets folder in my .minecraft help
