### ISSUE TITLE
exporting finished playing minecraft error

### ISSUE THREAD

**Issue by ICSHADOW** [Minecraftfunize/Youtube-Hacked-Client-1.8#19]
Exception in thread "main" java.lang.SecurityException: SHA-256 digest error for bsu.class
	at sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:218)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:241)
	at java.util.jar.JarVerifier.update(JarVerifier.java:228)
	at java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:482)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.client.main.Main.main(SourceFile:40)
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

Wtf help pls

**Comment by ukwilliam** [comment]
You should drag in the assets folder that you can find in an unmodded MC jar (extract it, get assets, extract modded jar, drop it in there, zip modded jar contents, rename to ?.jar, drag next to .json.)

Hope this helped!

**Comment by Minecraftfunize** [comment]
On Friday will do a video on how to export

**Comment by ukwilliam** [comment]
Cheers.

**Comment by ukwilliam** [comment]
@Minecraftfunize Hey man, It'd be really useful if you'd do a tutorial on how to make Capes, Nametags and maybe a Chest ESP. Great tutorials.

**Comment by Minecraftfunize** [comment]
Sure

**Comment by ukwilliam** [comment]
Cheers!

**Comment by HerryYT** [comment]
it won't fix error
