### ISSUE TITLE
Exporting Issue.

### ISSUE THREAD

**Issue by n1gger** [Minecraftfunize/Youtube-Hacked-Client-1.8#24]
Hey i watched your vids on the gui setup and i have added my own hacks etc but when i export it as jar, and remove meta-inf and Start.class and add assets, i crash when entering Single, or multiplayer world. Works fine on ecilipse but crashes on client, and the error is caused by Slicks unicodeFont. Ty if u help.﻿

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 19.1.2016 23:53
Description: Unexpected error

java.lang.NoClassDefFoundError: org/newdawn/slick/UnicodeFont
	at me.amateurz.Sethmumu.ttf.FontUtils.<init>(FontUtils.java:43)
	at me.amateurz.Sethmumu.ttf.FontUtils.<init>(FontUtils.java:35)
	at me.amateurz.Sethmumu.utils.Wrapper.<clinit>(Wrapper.java:13)
	at me.amateurz.Sethmumu.ui.GuiIngameHook.Hud(GuiIngameHook.java:34)
	at me.amateurz.Sethmumu.ui.GuiIngameHook.StartHud(GuiIngameHook.java:30)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:234)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1248)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1141)
	at net.minecraft.client.Minecraft.run(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(Main.java:114)
Caused by: java.lang.ClassNotFoundException: org.newdawn.slick.UnicodeFont
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by Ludde856x** [comment]
i get the same error!

**Comment by Minecraftfunize** [comment]
Watch the exporting video it should help that issue
